export const REGISTER_STRING = {
  emailOrUsername: "Email or Username",
  welcomeBack: "WELCOME BACK",
  loginIntoYourAccount: "Log into your account",
  enterYourEmailOrUsername: "Enter your email or username",
  password: "Password",
  forgotPassword: "Forgot password?",
  enterYourPassword: "Enter your password",
  loginNow: "Login now",
  notRegisteredYet: "Not registered yet?",
  registerArrow: "Register →",
  email: "Email",
  username: "Username",
  continue: "Continue",
  alreadyHaveAnAccount: "Already have an account?",
  loginArrow: "Login ->",
  signUp: "SIGN UP",
  createAnAccountToContinue: "Create an account to continue",
};
